### ISSUE TITLE
Building lipstick for X11, without Wayland

### ISSUE THREAD

**Issue by ViktorNova** [nemomobile/lipstick#301]
From my understanding, Lipstick (or at least it's ancestors) at some point in the past was released for both X11 and Wayland. I know X11 isn't the target display server now, but is it possible to built Lipstick as an X11 desktop for a standard Linux distribution like Debian, without Wayland? 

And if so, how to go about this? Thanks!

**Comment by rburchell** [comment]
No. Use with X11 hasn't been possible for a few years now.

You should be able to build on a "standard" distribution if you're also willing to build the necessary dependencies.

**Comment by ViktorNova** [comment]
Thank you for your response (and my apologies for my late response, I missed the notification)

So I wonder, are there certain parts of Nemo (such as, for instance, parts of the control panel or connman configurator) that might be used inside X11, without the entire Nemo stack managing the whole desktop present?

The reason I'm asking is that I'm building a touch environment that will run on very minimal hardware that must use X11. I'm having a hard time finding system config tools that are touch friendly, but there has been a lot of good work done on Nemo and Meego Touch to make nice touch UIs for these tasks, and I would love to re-use as much of this stuff as possible.

If this isn't possible with the current project, perhaps someone could point me to the latest code that worked on X11?  What was the big change that broke compatibility?

Thanks a bunch!
