### ISSUE TITLE
Orientation of screenshotService saved images

### ISSUE THREAD

**Issue by kimmoli** [nemomobile/lipstick#350]
Allow either controlling the rotation of saved QPixmap, or rotate it automatically according to current UI/Device orientation.

**Comment by matthewvogt** [comment]
Any reason to make it configurable, or should the current UI rotation always be sufficient, do you think?

**Comment by kimmoli** [comment]
Current orientation is enough for me.
Making it configurable breaks dbus api? unless new method to control this is added.

**Comment by matthewvogt** [comment]
Raised for this issue: https://bugs.merproject.org/show_bug.cgi?id=1139

**Comment by kimmoli** [comment]
Fixed with #352
